set.seed(20260813); dir.create("data",FALSE);dir.create("output",FALSE);dir.create("figures",FALSE);dir.create("docs",FALSE)
n<-1200; d<-data.frame(id=1:n,treatment=factor(rbinom(n,1,.5),0:1,c("Control","Treatment")),age=rnorm(n,64,10),severity=rnorm(n))
x<-as.integer(d$treatment)-1; t1<-rexp(n,exp(-3.5-.45*x+.02*(d$age-64)+.35*d$severity)); t2<-rexp(n,exp(-4+.12*x+.018*(d$age-64))); cen<-runif(n,3,8)
d$time<-pmin(t1,t2,cen);d$status<-ifelse(d$time==t1,1,ifelse(d$time==t2,2,0));write.csv(d,"data/time_to_event.csv",row.names=FALSE)
cox<-survival::coxph(survival::Surv(time,status==1)~treatment+age+severity,data=d); z<-survival::cox.zph(cox)
r<-summary(cox)$coef["treatmentTreatment",]
d$event<-factor(d$status,levels=0:2,labels=c("censor","disease","other"));fgd<-survival::finegray(survival::Surv(time,event)~treatment+age+severity,data=d,etype="disease");fg<-survival::coxph(survival::Surv(fgstart,fgstop,fgstatus)~treatment+age+severity,weight=fgwt,data=fgd);fr<-summary(fg)$coef["treatmentTreatment",]
out<-data.frame(model=c("Cause-specific Cox: disease event","Fine-Gray subdistribution: disease event"),hazard_ratio=exp(c(r["coef"],fr["coef"])),lower=exp(c(r["coef"]-1.96*r["se(coef)"],fr["coef"]-1.96*fr["se(coef)"])),upper=exp(c(r["coef"]+1.96*r["se(coef)"],fr["coef"]+1.96*fr["se(coef)"])),p_value=c(r["Pr(>|z|)"],fr["Pr(>|z|)"]))
write.csv(out,"output/model_results.csv",row.names=FALSE); capture.output(z,file="output/proportional-hazards-check.txt")
sf<-survival::survfit(survival::Surv(time,status==1)~treatment,data=d); png("figures/kaplan-meier.png",900,600);plot(sf,col=c("#555555","#0072B2"),lwd=3,xlab="Years",ylab="Event-free probability",main="Kaplan-Meier: Disease Event");legend("bottomleft",levels(d$treatment),col=c("#555555","#0072B2"),lwd=3);dev.off()
stopifnot(nrow(d)==1200,sum(d$status==2)>0,all(out$hazard_ratio<1))
html<-sprintf('<!doctype html><meta charset="utf-8"><style>body{font:16px Arial;max-width:900px;margin:40px auto;color:#111;line-height:1.5}img{max-width:100%%}</style><h1>Survival and Competing-Risk Analysis</h1><p><b>Question:</b> Is treatment associated with time to the disease event when other-cause events compete?</p><h2>Methods</h2><p>We simulated 1,200 participants with censoring and two mutually exclusive event types. The primary model is an adjusted cause-specific Cox model; Kaplan-Meier estimates and Schoenfeld-residual diagnostics support model review.</p><h2>Result</h2><p>Adjusted disease-event HR: <b>%.2f</b> (95%% CI %.2f–%.2f; p=%.3g).</p><img src="../figures/kaplan-meier.png"><h2>Interpretation</h2><p>The cause-specific hazard ratio answers an etiologic rate question. Competing events are retained explicitly in the dataset and should not be interpreted as ordinary noninformative censoring for absolute-risk questions.</p><h2>Reproducibility</h2><p>Run <code>Rscript run_all.R</code>. Data are synthetic.</p>',out$hazard_ratio,out$lower,out$upper,out$p_value);writeLines(html,"docs/index.html")
